# Generated by Django 5.0.6 on 2024-07-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_version_active",
            field=models.BooleanField(
                default=True,
                help_text="является ли версия активной",
                verbose_name="Активная версия",
            ),
        ),
    ]
